/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [NewReleases]    Script Date: 9/8/2017 11:11:36 PM ******/
DROP DATABASE [NewReleases]
GO

/****** Object:  Database [NewReleases]    Script Date: 9/8/2017 11:11:36 PM ******/
CREATE DATABASE [NewReleases]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewReleases', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\NewReleases.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewReleases_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS01\MSSQL\DATA\NewReleases_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NewReleases] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewReleases].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewReleases] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewReleases] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewReleases] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewReleases] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewReleases] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewReleases] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NewReleases] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewReleases] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewReleases] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewReleases] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewReleases] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewReleases] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewReleases] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewReleases] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewReleases] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NewReleases] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewReleases] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewReleases] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewReleases] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewReleases] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewReleases] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NewReleases] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewReleases] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NewReleases] SET  MULTI_USER 
GO

ALTER DATABASE [NewReleases] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewReleases] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewReleases] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NewReleases] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NewReleases] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NewReleases] SET QUERY_STORE = OFF
GO

USE [NewReleases]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [NewReleases] SET  READ_WRITE 
GO


